nmMode: hardlinks-global
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

packageExtensions:
  "@xstate/tools-shared@*":
    dependencies:
      "prettier": "*"
  "@xstate/machine-extractor@*":
    dependencies:
      "@babel/core": "*"
